const $ = (s, root = document) => root.querySelector(s);
const $$ = (s, root = document) => [...root.querySelectorAll(s)];
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid = () => crypto.randomUUID();
const dayKey = (d = new Date()) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const today = () => dayKey();
const clone = x => JSON.parse(JSON.stringify(x));
const paths = {
 home:'M3 10l9-7 9 7M5 9v12h5v-7h4v7h5V9',
 today:'M8 2v4M16 2v4M3 10h18M5 4h14a2 2 0 0 1 2 2v14H3V6a2 2 0 0 1 2-2M8 14h3M8 17h7',
 project:'M3 7h7l2-3h9v16H3z',
 calendar:'M8 2v4M16 2v4M3 10h18M5 4h14a2 2 0 0 1 2 2v14H3V6a2 2 0 0 1 2-2M7 14h2M12 14h2M17 14h1M7 17h2M12 17h2',
 page:'M14 2H5v20h14V7zM14 2v5h5M8 12h8M8 16h6',
 settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M5 19l2-2M17 7l2-2',
 plus:'M12 5v14M5 12h14', lock:'M5 10h14v11H5zM8 10V6a4 4 0 0 1 8 0v4M12 14v3',
 arrow:'M5 12h14M14 7l5 5-5 5', left:'M15 5l-7 7 7 7', right:'M9 5l7 7-7 7',
 check:'M5 12l4 4L19 6', edit:'M15 4l5 5-11 11H4v-5zM13 6l5 5',
 trash:'M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7M14 10v7',
 up:'M6 15l6-6 6 6', down:'M6 9l6 6 6-6', close:'M6 6l12 12M18 6L6 18',
 menu:'M4 6h16M4 12h16M4 18h16', logout:'M10 4H4v16h6M8 12h13M16 7l5 5-5 5',
 link:'M10 13a5 5 0 0 0 7 0l3-3a5 5 0 0 0-7-7l-2 2M14 11a5 5 0 0 0-7 0l-3 3a5 5 0 0 0 7 7l2-2',
 download:'M12 3v12M7 10l5 5 5-5M4 16v5h16v-5', grip:'M8 5h.01M16 5h.01M8 12h.01M16 12h.01M8 19h.01M16 19h.01',
 moon:'M21 13A9 9 0 0 1 11 3a9 9 0 1 0 10 10', refresh:'M20 7V3l-3 3M4 17v4l3-3M20 7a8 8 0 0 0-14-2M4 17a8 8 0 0 0 14 2',
 search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14M15 15l6 6'
};
const icon = name => `<svg class="ico" aria-hidden="true" viewBox="0 0 24 24"><path d="${paths[name] || paths.page}"/></svg>`;
const btn = (text, action, kind='', extra='') => `<button class="btn ${kind}" data-action="${action}" ${extra}>${text}</button>`;
const ibtn = (name, action, label, extra='') => `<button class="icon-btn" data-action="${action}" aria-label="${esc(label)}" title="${esc(label)}" ${extra}>${icon(name)}</button>`;
const empty = (name, action, label) => `<div class="empty">${icon(name)}${action ? btn(`${icon('plus')}${label}`,action,'small') : ''}</div>`;
const defaultProfile = () => ({name:'',tagline:'',bio:'',github:'',email:'',projects:[],style:'studio'});
const defaultData = () => ({tasks:[],projects:[],pages:[],categories:[],note:'',settings:{accent:'#4b63df',density:'comfortable',dashboard:['tasks','agenda','projects','note']}});
let config = {...window.SPACE_CONFIG};
try { config = {...config, ...JSON.parse(localStorage.getItem('space-connection') || '{}')}; } catch {}
const state = {profile:defaultProfile(),data:null,user:null,db:null,preview:false,view:'today',projectId:null,pageId:null,month:new Date(new Date().getFullYear(),new Date().getMonth(),1),selectedDay:today(),status:'',revision:0,generation:0,dirty:false,saving:false,conflict:false,filter:'',query:'',calendarId:'primary',calendars:[],events:[],token:null,tokenExpiry:0,menu:false,loading:false};
let saveTimer, toastTimer;
function toast(message){const el=$('#toast');el.textContent=message;el.style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.style.display='none',4000);}
function safeUrl(url){try{const u=new URL(url);return ['https:','http:','mailto:'].includes(u.protocol)?u.href:'#';}catch{return '#';}}
function profileValue(){return state.profile || defaultProfile();}
function applyTheme(){const settings=state.data?.settings;document.documentElement.style.setProperty('--accent',settings?.accent || '#4b63df');document.documentElement.style.setProperty('--accent-soft',`${settings?.accent || '#4b63df'}12`);document.documentElement.style.setProperty('--space',settings?.density==='compact'?'20px':'28px');document.documentElement.style.setProperty('--radius',settings?.density==='compact'?'12px':'18px');}
function saveStatus(){const el=$('.save-status');if(el){el.textContent=state.preview?'미리보기 · 저장되지 않음':state.status;el.classList.toggle('error',state.conflict || state.status.startsWith('저장 실패'));}}
function touch(){if(!state.data)return;if(state.preview){saveStatus();return;}state.dirty=true;state.generation++;state.status='저장 대기';saveStatus();clearTimeout(saveTimer);saveTimer=setTimeout(flush,650);}
async function flush(){
 if(!state.user || !state.db || !state.dirty || state.saving || state.conflict)return;
 const owner=state.user.id, generation=state.generation, data=clone(state.data),revision=state.revision;
 state.saving=true;state.status='저장 중';saveStatus();
 try{const {data:rows,error}=await state.db.from('private_workspace').update({data,revision:revision+1,updated_at:new Date().toISOString()}).eq('owner_id',owner).eq('revision',revision).select('revision');if(error)throw error;if(!rows?.length){state.conflict=true;throw new Error('다른 창에서 수정되었습니다. 백업 후 다시 불러와 주세요.');}if(state.user?.id!==owner)return;state.revision=rows[0].revision;state.dirty=state.generation!==generation;state.status=state.dirty?'저장 대기':'저장됨';}
 catch(error){if(state.user?.id===owner){state.status=`저장 실패 · ${error.message}`;toast(state.status);}}
 finally{state.saving=false;saveStatus();if(state.dirty && !state.conflict && state.status==='저장 대기')setTimeout(flush,0);}
}
function render(){applyTheme();const route=location.hash.slice(1)||'home';if(route==='home'){renderPublic();return;}if(!state.user&&!state.preview){renderLogin();return;}if(!state.data){$('#app').innerHTML='<div class="login-shell"><p class="muted">불러오는 중</p></div>';return;}const allowed=['today','projects','calendar','pages','settings'];state.view=allowed.includes(route)?route:'today';renderWorkspace();}
function renderPublic(){
 const p=profileValue(),canEdit=!!state.user||state.preview;
 const blank=`<div class="blank-copy" aria-hidden="true"><div class="blank-title"></div><div class="blank-line"></div><div class="blank-line short"></div></div>`;
 $('#app').innerHTML=`<div class="public" data-style="${esc(p.style)}"><header class="public-nav"><a href="#home" class="brand"><span class="brand-mark">P</span> PORTFOLIO</a><nav><a class="active" href="#home">소개</a><a href="#today">플래너 ${icon('lock')}</a></nav></header>${canEdit?`<div class="public-editor-bar"><span>${state.preview?'템플릿 미리보기':'공개 페이지 편집'}</span><div class="row">${btn(`${icon('edit')} 내용 편집`,'edit-profile','small')}${btn('작업 공간','workspace','small')}</div></div>`:''}<section class="public-hero"><div class="hero-copy"><div class="eyebrow">PORTFOLIO</div>${p.name?`<h1>${esc(p.name)}</h1>${p.tagline?`<p>${esc(p.tagline)}</p>`:''}`:blank}${p.github||p.email?`<div class="row">${p.github?`<a class="btn small" href="${esc(safeUrl(p.github))}" target="_blank" rel="noopener noreferrer">GitHub ${icon('arrow')}</a>`:''}${p.email?`<a class="btn small" href="mailto:${esc(p.email)}">연락 ${icon('arrow')}</a>`:''}</div>`:''}</div><div class="hero-art" aria-hidden="true"><div class="orbit"></div><div class="orbit two"></div><div class="orbit three"></div><div class="sphere"></div><div class="orbital-dot"></div></div></section><div class="public-grid"><section class="card"><div class="section-label"><h2>소개</h2><span>01</span></div>${p.bio?`<p style="white-space:pre-wrap">${esc(p.bio)}</p>`:`<div class="template-slot" aria-hidden="true"><div class="skeleton-grid"><div class="blank-line"></div><div class="blank-line"></div><div class="blank-line short"></div></div></div>`}</section><section class="card"><div class="section-label"><h2>프로젝트</h2><span>02</span></div>${p.projects.length?p.projects.map(x=>`<article class="public-project"><h3>${esc(x.title)}</h3>${x.description?`<p>${esc(x.description)}</p>`:''}${x.url?`<a class="text-btn tiny" href="${esc(safeUrl(x.url))}" target="_blank" rel="noopener noreferrer">열기 ${icon('arrow')}</a>`:''}</article>`).join(''):`<div class="template-slot" aria-hidden="true"><div class="skeleton-grid"><div class="blank-line" style="width:50%"></div><div class="blank-line" style="width:85%"></div><div class="blank-line short"></div></div></div>`}</section></div><footer class="public-footer"><span>PORTFOLIO / WORKSPACE</span><a href="#today">${icon('lock')} 개인 공간</a></footer></div>${!state.user&&!state.preview?`<button class="template-preview" data-action="preview">${icon('settings')} 템플릿 미리보기</button>`:''}`;
}
function renderLogin(){const configured=!!(config.supabaseUrl&&config.supabaseKey);$('#app').innerHTML=`<div class="login-shell"><section class="card login-card"><a class="brand" href="#home"><span class="brand-mark">P</span> WORKSPACE</a><div class="row" style="margin-bottom:18px;color:var(--accent)">${icon('lock')}</div><h1>개인 플래너</h1><p>비밀번호를 입력해 주세요.</p><form id="login-form"><label class="field"><span>비밀번호</span><input type="password" name="password" autocomplete="current-password" required aria-label="비밀번호" ${configured?'':'disabled'}></label><div class="form-error" role="alert" id="login-error"></div><button class="btn primary" type="submit" ${configured?'':'disabled'}>들어가기 ${icon('arrow')}</button></form>${!configured?'<div class="connection-note">계정 연결 후 사용할 수 있습니다.</div>':''}<div class="login-links"><a href="#home">소개로 돌아가기</a><button data-action="connection">연결 설정</button></div><div style="margin-top:24px;text-align:center">${btn('저장 없이 화면 살펴보기','preview','small')}</div></section></div>`;}
const titles={today:'오늘',projects:'프로젝트',calendar:'캘린더',pages:'페이지',settings:'설정'};
function renderWorkspace(){const nav=Object.entries(titles).map(([key,label])=>`<a href="#${key}" class="nav-item ${state.view===key?'active':''}">${icon(key==='projects'?'project':key==='pages'?'page':key)}${label}</a>`).join('');$('#app').innerHTML=`<div class="workspace ${state.menu?'menu-open':''}"><aside class="sidebar"><a class="brand" href="#home"><span class="brand-mark">P</span> WORKSPACE</a><div class="workspace-label">PERSONAL SPACE</div><nav>${nav}</nav><div class="sidebar-bottom"><a class="nav-item" href="#home">${icon('home')} 공개 페이지</a><button class="nav-item" data-action="${state.preview?'exit-preview':'logout'}">${icon('logout')}${state.preview?'미리보기 종료':'로그아웃'}</button><div class="sidebar-user"><div class="avatar">${icon('lock')}</div><div><h3>개인 공간</h3><span class="tiny muted">${state.preview?'미리보기':'비공개'}</span></div></div></div></aside><main class="main"><header class="topbar"><div class="row"><span class="mobile-toggle">${ibtn('menu','toggle-menu','메뉴 열기')}</span><div class="breadcrumb">Workspace <span>/</span> <b>${titles[state.view]}</b></div></div><span class="save-status"></span></header>${state.preview?'<div class="preview-banner"><span>미리보기에서 입력한 내용은 저장되지 않습니다.</span><button data-action="connection">계정 연결</button></div>':''}<div class="content">${({today:viewToday,projects:viewProjects,calendar:viewCalendar,pages:viewPages,settings:viewSettings}[state.view])()}</div></main></div>`;saveStatus();resizeTextareas();}
function heading(title,eyebrow,actions=''){return `<div class="page-heading"><div><div class="eyebrow">${eyebrow}</div><h1>${esc(title)}</h1></div><div class="row">${actions}</div></div>`;}
function category(id){return state.data.categories.find(c=>c.id===id);}
function categoryTag(id){const c=category(id);return c?`<span class="pill" style="background:${esc(c.color)}15;color:${esc(c.color)}">${esc(c.name)}</span>`:'';}
function taskRow(t){return `<div class="task-row ${t.status==='done'?'done':''}"><input type="checkbox" aria-label="완료 상태" data-change="task-check" data-id="${t.id}" ${t.status==='done'?'checked':''}><button class="task-title" data-action="edit-task" data-id="${t.id}">${esc(t.title)}</button>${categoryTag(t.categoryId)}<span class="task-meta">${esc(t.due||'')}</span>${ibtn('edit','edit-task','할 일 편집',`data-id="${t.id}"`)}</div>`;}
function projectCard(p){const tasks=state.data.tasks.filter(t=>t.projectId===p.id),done=tasks.filter(t=>t.status==='done').length;return `<article class="card project-card" data-action="open-project" data-id="${p.id}" tabindex="0" role="button" aria-label="${esc(p.title)}"><div class="project-top"><div class="project-symbol" style="color:${esc(p.color)};background:${esc(p.color)}12">${icon('project')}</div>${categoryTag(p.categoryId)}</div><h2>${esc(p.title)}</h2>${p.description?`<p>${esc(p.description)}</p>`:''}<div class="project-bottom"><span>${done} / ${tasks.length}</span><span>${esc(p.due||'')}</span></div><div class="progress-track"><div class="progress-fill" style="width:${tasks.length?done/tasks.length*100:0}%;background:${esc(p.color)}"></div></div></article>`;}
function viewToday(){const tasks=state.data.tasks.filter(t=>t.due===today() || !t.due),events=eventsOn(today()),projects=state.data.projects;const widgets={tasks:`<section class="card"><div class="card-head"><div class="row"><h2>할 일</h2><span class="count">${tasks.filter(t=>t.status!=='done').length}</span></div>${ibtn('plus','add-task','할 일 추가')}</div>${tasks.length?tasks.map(taskRow).join(''):empty('check')}<form class="quick-form" id="quick-task"><label class="visually-hidden" for="quick-title">할 일</label><input id="quick-title" name="title" autocomplete="off" required maxlength="300"><button class="btn small" aria-label="할 일 추가">${icon('plus')}</button></form></section>`,agenda:`<section class="card"><div class="card-head"><h2>일정</h2><a href="#calendar" class="text-btn">${icon('arrow')}</a></div>${events.length?events.map(agendaItem).join(''):empty('calendar',state.token?null:'google-connect',state.preview?'캘린더 연결':'Google 캘린더 연결')}</section>`,projects:`<section class="card wide"><div class="card-head"><div class="row"><h2>프로젝트</h2><span class="count">${projects.length}</span></div>${btn(`${icon('plus')} 프로젝트`,'add-project','small')}</div>${projects.length?`<div class="project-grid">${projects.map(projectCard).join('')}</div>`:empty('project')}</section>`,note:`<section class="card wide"><div class="card-head"><h2>메모</h2>${icon('edit')}</div><label class="visually-hidden" for="daily-note">메모</label><textarea id="daily-note" class="note-area" data-input="note">${esc(state.data.note)}</textarea></section>`};return heading('오늘',new Date().toLocaleDateString('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'long'}),btn(`${icon('plus')} 할 일`,'add-task','primary'))+`<div class="dashboard-grid">${state.data.settings.dashboard.map(x=>widgets[x]).join('')}</div>`;}
function viewProjects(){const p=state.data.projects.find(p=>p.id===state.projectId);if(p)return viewProject(p);const projects=state.data.projects.filter(p=>(!state.filter||p.categoryId===state.filter)&&(!state.query||p.title.toLowerCase().includes(state.query.toLowerCase())));return heading('프로젝트','PROJECTS',btn(`${icon('plus')} 프로젝트`,'add-project','primary'))+`<div class="toolbar"><label class="visually-hidden" for="project-filter">분류</label><select id="project-filter" data-change="project-filter"><option value="">전체</option>${state.data.categories.map(c=>`<option value="${c.id}" ${state.filter===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select><label class="visually-hidden" for="project-search">검색</label><input id="project-search" type="search" aria-label="검색" data-input="project-search" value="${esc(state.query)}"></div>${projects.length?`<div class="project-grid">${projects.map(projectCard).join('')}</div>`:`<div class="card">${empty('project','add-project','프로젝트 추가')}</div>`}`;}
function viewProject(p){const tasks=state.data.tasks.filter(t=>t.projectId===p.id);return `<button class="text-btn row" data-action="projects-back" style="margin-bottom:20px">${icon('left')} 프로젝트</button>`+heading(p.title,'PROJECT',`${btn(`${icon('edit')} 편집`,'edit-project','',`data-id="${p.id}"`)}${btn(`${icon('plus')} 할 일`,'add-task','primary',`data-project="${p.id}"`)}`)+`${p.description?`<p class="muted" style="white-space:pre-wrap;margin-bottom:20px">${esc(p.description)}</p>`:''}<div class="row">${categoryTag(p.categoryId)}${p.due?`<span class="tiny muted">${esc(p.due)}</span>`:''}</div><div class="board">${[['todo','할 일'],['doing','진행 중'],['done','완료']].map(([status,label])=>`<section class="column" data-drop="task" data-status="${status}" data-project="${p.id}"><div class="column-head"><span>${label} <span class="count">${tasks.filter(t=>t.status===status).length}</span></span>${ibtn('plus','add-task','할 일 추가',`data-status="${status}" data-project="${p.id}"`)}</div>${tasks.filter(t=>t.status===status).map(t=>`<article class="board-task" draggable="true" data-drag="task" data-id="${t.id}"><button data-action="edit-task" data-id="${t.id}" style="text-align:left;width:100%"><h3>${esc(t.title)}</h3>${t.due?`<div class="task-meta">${esc(t.due)}</div>`:''}</button><label class="visually-hidden" for="status-${t.id}">상태</label><select id="status-${t.id}" data-change="task-status" data-id="${t.id}" style="font-size:10px;padding:4px;margin-top:12px"><option value="todo" ${t.status==='todo'?'selected':''}>할 일</option><option value="doing" ${t.status==='doing'?'selected':''}>진행 중</option><option value="done" ${t.status==='done'?'selected':''}>완료</option></select></article>`).join('')}</section>`).join('')}</div>`;}
function eventsOn(key){const all=[...state.data.tasks.filter(t=>t.due===key).map(t=>({id:t.id,title:t.title,date:key,source:'task',status:t.status})),...state.events.filter(ev=>{const start=ev.start.date||dayKey(new Date(ev.start.dateTime));const end=ev.end.date||dayKey(new Date(ev.end.dateTime));return start===key || (start<key&&(ev.end.date?key<end:key<=end));})];return all;}
function agendaItem(ev){const google=ev.source!=='task',time=google?(ev.start.date?'종일':new Date(ev.start.dateTime).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})):'할 일';const url=google?safeUrl(ev.htmlLink||'https://calendar.google.com'):'#';return `<div class="agenda-item"><span class="tiny">${esc(time)} ${google?'· Google':''}</span>${google?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer"><h3>${esc(ev.summary||'제목 없음')} ${icon('arrow')}</h3></a>`:`<button data-action="edit-task" data-id="${ev.id}" style="text-align:left"><h3>${esc(ev.title)}</h3></button>`}</div>`;}
function viewCalendar(){const month=state.month,start=new Date(month.getFullYear(),month.getMonth(),1);start.setDate(start.getDate()-start.getDay());const days=Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);const key=dayKey(d),evs=eventsOn(key);return `<button class="day ${d.getMonth()!==month.getMonth()?'out':''} ${key===today()?'today':''} ${key===state.selectedDay?'selected':''}" data-action="select-day" data-day="${key}" aria-label="${key}"><span class="day-number">${d.getDate()}</span>${evs.slice(0,3).map(ev=>`<span class="cal-event ${ev.source==='task'?'':'google'}">${esc(ev.title||ev.summary||'제목 없음')}</span>`).join('')}${evs.length>3?`<span class="tiny muted">+${evs.length-3}</span>`:''}</button>`;}).join('');const events=eventsOn(state.selectedDay);return heading('캘린더','CALENDAR',`${state.token?btn(`${icon('refresh')} 새로고침`,'calendar-refresh'):btn(`${icon('link')} Google 연결`,'google-connect')}`)+`<div class="calendar-shell"><section class="card calendar-card"><div class="calendar-toolbar"><div class="row">${ibtn('left','month-prev','이전 달')}<h2>${month.getFullYear()}년 ${month.getMonth()+1}월</h2>${ibtn('right','month-next','다음 달')}</div>${btn('오늘','month-today','small')}</div><div class="calendar-grid">${['일','월','화','수','목','금','토'].map(w=>`<div class="weekday">${w}</div>`).join('')}${days}</div></section><aside><section class="card"><div class="card-head"><h2>${esc(state.selectedDay.slice(5).replace('-',' / '))}</h2>${ibtn('plus','add-task','할 일 추가',`data-day="${state.selectedDay}"`)}</div>${events.length?events.map(agendaItem).join(''):empty('calendar')}</section><section class="card link-card"><div class="row"><span class="dot" style="background:#4c9b7e"></span><h3>Google 캘린더</h3></div>${state.token?`<div style="margin-top:15px"><label class="visually-hidden" for="google-calendar">Google 캘린더 선택</label><select id="google-calendar" data-change="calendar-select">${state.calendars.map(c=>`<option value="${esc(c.id)}" ${c.id===state.calendarId?'selected':''}>${esc(c.summary)}</option>`).join('')}</select></div>${btn('연결 해제','google-disconnect','small')}`:`${btn(`${icon('link')} 계정 연결`,'google-connect','small')}`}<a class="text-btn tiny" style="display:block;text-align:center;margin-top:10px" href="https://calendar.google.com" target="_blank" rel="noopener noreferrer">Google 캘린더 열기 ${icon('arrow')}</a></section></aside></div>`;}
function blockHTML(b,i){return `<div class="block ${b.type} ${b.checked?'checked':''}" draggable="true" data-drag="block" data-id="${b.id}" data-drop="block"><div class="block-controls">${ibtn('up','block-up','위로 이동',`data-id="${b.id}"`)}${ibtn('down','block-down','아래로 이동',`data-id="${b.id}"`)}${ibtn('trash','block-delete','블록 삭제',`data-id="${b.id}"`)}</div><div class="block-main">${b.type==='check'?`<input type="checkbox" aria-label="완료 상태" data-change="block-check" data-id="${b.id}" ${b.checked?'checked':''}>`:b.type==='bullet'?'<span aria-hidden="true">•</span>':''}${b.type==='divider'?'':`<textarea class="block-text" rows="1" data-input="block" data-id="${b.id}" aria-label="${{heading:'제목',text:'본문',check:'체크리스트',bullet:'목록',quote:'인용',callout:'강조'}[b.type]||'본문'} ${i+1}">${esc(b.text)}</textarea>`}</div></div>`;}
function viewPages(){const pages=state.data.pages;if(!pages.some(p=>p.id===state.pageId))state.pageId=pages[0]?.id;const current=pages.find(p=>p.id===state.pageId);return heading('페이지','PAGES',btn(`${icon('plus')} 페이지`,'add-page','primary'))+`<div class="page-layout"><aside class="card page-list">${pages.length?pages.map(p=>`<button class="page-item ${p.id===state.pageId?'active':''}" data-action="open-page" data-id="${p.id}">${icon('page')}<span>${esc(p.title||'제목 없음')}</span>${p.favorite?'<span class="dot"></span>':''}</button>`).join(''):empty('page')}</aside><section class="card document">${current?`<div class="document-header"><label class="visually-hidden" for="page-title">페이지 제목</label><input id="page-title" class="document-title" value="${esc(current.title)}" data-input="page-title" maxlength="300"><div class="row">${ibtn('check','page-favorite',current.favorite?'고정 해제':'고정',`data-id="${current.id}"`)}${ibtn('trash','page-delete','페이지 삭제',`data-id="${current.id}"`)}</div></div><div class="blocks">${current.blocks.map(blockHTML).join('')}</div><div class="block-types">${[['text','본문'],['heading','제목'],['check','체크리스트'],['bullet','목록'],['quote','인용'],['callout','강조'],['divider','구분선']].map(([type,label])=>btn(`${icon('plus')}${label}`,'add-block','small',`data-type="${type}"`)).join('')}</div>`:empty('page','add-page','페이지 추가')}</section></div>`;}
function viewSettings(){const s=state.data.settings;return heading('설정','SETTINGS')+`<div class="settings-grid"><section class="card"><div class="card-head"><h2>화면</h2></div><div class="setting-row"><h3>포인트 색상</h3><input aria-label="포인트 색상" type="color" value="${esc(s.accent)}" data-change="accent"></div><div class="setting-row"><h3>여백</h3><select aria-label="여백" data-change="density"><option value="comfortable" ${s.density==='comfortable'?'selected':''}>넉넉하게</option><option value="compact" ${s.density==='compact'?'selected':''}>촘촘하게</option></select></div><div class="setting-row"><h3>공개 페이지</h3>${btn('편집','edit-profile','small')}</div></section><section class="card"><div class="card-head"><h2>오늘 화면 순서</h2></div>${s.dashboard.map((key,i)=>`<div class="setting-row"><h3>${{tasks:'할 일',agenda:'일정',projects:'프로젝트',note:'메모'}[key]}</h3><div class="row">${ibtn('up','widget-up','위로 이동',`data-key="${key}" ${i===0?'disabled':''}`)}${ibtn('down','widget-down','아래로 이동',`data-key="${key}" ${i===s.dashboard.length-1?'disabled':''}`)}</div></div>`).join('')}</section><section class="card"><div class="card-head"><h2>분류</h2>${ibtn('plus','add-category','분류 추가')}</div>${state.data.categories.length?state.data.categories.map(c=>`<div class="category-row"><input aria-label="분류 이름" value="${esc(c.name)}" data-input="category-name" data-id="${c.id}" maxlength="80"><input aria-label="분류 색상" type="color" value="${esc(c.color)}" data-change="category-color" data-id="${c.id}">${ibtn('trash','delete-category','분류 삭제',`data-id="${c.id}"`)}</div>`).join(''):empty('project','add-category','분류 추가')}</section><section class="card"><div class="card-head"><h2>연결 · 백업</h2></div><div class="setting-row"><h3>계정 연결</h3>${btn('설정','connection','small')}</div><div class="setting-row"><h3>Google 캘린더</h3>${btn(state.token?'연결 해제':'연결',state.token?'google-disconnect':'google-connect','small')}</div><div class="setting-row"><h3>데이터 백업</h3>${btn(`${icon('download')} 내보내기`,'export','small')}</div><div class="setting-row"><h3>백업 복원</h3>${btn('파일 선택','import','small')}<input id="import-file" type="file" accept="application/json,.json" hidden></div>${!state.preview?`<div class="setting-row"><h3>저장 상태</h3><div class="row">${btn('다시 저장','retry-save','small')}${btn('다시 불러오기','reload-data','small')}</div></div>`:''}</section></div>`;}
function resizeTextareas(){for(const el of $$('.block-text')){el.style.height='auto';el.style.height=Math.max(26,el.scrollHeight)+'px';}}
function modal(title,body){$('#modal-content').innerHTML=`<div class="modal-body"><div class="modal-head"><h2>${esc(title)}</h2>${ibtn('close','modal-close','닫기')}</div>${body}</div>`;$('#modal').showModal();}
const field=(label,name,value='',type='text',required=false)=>`<label class="field"><span>${label}</span><input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''}></label>`;
const area=(label,name,value='')=>`<label class="field"><span>${label}</span><textarea name="${name}">${esc(value)}</textarea></label>`;
function options(items,value){return `<option value="">없음</option>${items.map(x=>`<option value="${x.id}" ${x.id===value?'selected':''}>${esc(x.name||x.title||'제목 없음')}</option>`).join('')}`;}
function taskModal(id,extra={}){const t=state.data.tasks.find(x=>x.id===id)||{title:'',due:extra.day||today(),status:extra.status||'todo',projectId:extra.project||'',categoryId:'',description:''};modal(id?'할 일 편집':'할 일 추가',`<form id="task-form" data-id="${id||''}">${field('할 일','title',t.title,'text',true)}${area('메모','description',t.description)}<div class="two-fields">${field('날짜','due',t.due,'date')}<label class="field"><span>상태</span><select name="status">${[['todo','할 일'],['doing','진행 중'],['done','완료']].map(([key,label])=>`<option value="${key}" ${t.status===key?'selected':''}>${label}</option>`).join('')}</select></label><label class="field"><span>프로젝트</span><select name="projectId">${options(state.data.projects,t.projectId)}</select></label><label class="field"><span>분류</span><select name="categoryId">${options(state.data.categories,t.categoryId)}</select></label></div><div class="modal-actions">${id?btn('삭제','delete-task','danger',`data-id="${id}"`):''}<button class="btn primary" type="submit">저장</button></div></form>`);}
function projectModal(id){const p=state.data.projects.find(x=>x.id===id)||{title:'',description:'',due:'',categoryId:'',color:'#4b63df'};modal(id?'프로젝트 편집':'프로젝트 추가',`<form id="project-form" data-id="${id||''}">${field('프로젝트 이름','title',p.title,'text',true)}${area('설명','description',p.description)}<div class="two-fields">${field('마감일','due',p.due,'date')}<label class="field"><span>분류</span><select name="categoryId">${options(state.data.categories,p.categoryId)}</select></label></div>${field('색상','color',p.color,'color')}<div class="modal-actions">${id?btn('삭제','delete-project','danger',`data-id="${id}"`):''}<button class="btn primary" type="submit">저장</button></div></form>`);}
function profileModal(){const p=profileValue();modal('공개 페이지 편집',`<form id="profile-form">${field('이름 · 제목','name',p.name)}${field('한 줄 소개','tagline',p.tagline)}${area('소개','bio',p.bio)}<div class="two-fields">${field('GitHub 주소','github',p.github,'url')}${field('연락 이메일','email',p.email,'email')}</div><label class="field"><span>레이아웃</span><select name="style">${[['studio','스튜디오'],['minimal','미니멀'],['editorial','에디토리얼']].map(([key,label])=>`<option value="${key}" ${p.style===key?'selected':''}>${label}</option>`).join('')}</select></label><div class="row between"><h3>공개 프로젝트</h3>${btn(`${icon('plus')} 추가`,'profile-project-add','small')}</div><div id="public-project-fields">${p.projects.map(publicProjectFields).join('')}</div><div class="connection-note">여기에 저장한 내용은 공개 소개 페이지에 표시됩니다.</div><div class="form-error" id="profile-error" role="alert"></div><div class="modal-actions"><button class="btn primary" type="submit">${state.preview?'미리보기에 적용':'공개 페이지 저장'}</button></div></form>`);}
function publicProjectFields(p={title:'',description:'',url:''}){return `<div class="public-project-fields stack" style="padding:15px 0;border-top:1px solid var(--line)">${field('제목','public-title',p.title)}${area('설명','public-description',p.description)}${field('링크','public-url',p.url,'url')}${btn('삭제','profile-project-remove','small danger')}</div>`;}
function connectionModal(){modal('연결 설정',`<form id="connection-form">${field('Supabase 프로젝트 URL','supabaseUrl',config.supabaseUrl,'url',true)}${field('Supabase 공개 키','supabaseKey',config.supabaseKey,'text',true)}${field('Google OAuth 클라이언트 ID','googleClientId',config.googleClientId)}<p class="tiny muted">비밀번호는 이 설정에 저장하지 않습니다. 배포 전 아래 설정 파일을 내려받아 저장소의 config.js를 교체해 주세요.</p><ol class="help-list"><li>Supabase에서 사용자 계정을 만들고, 함께 제공한 SQL을 실행한 뒤 소유자 UUID를 등록합니다.</li><li>Google Cloud에서 Calendar API를 켜고 웹 OAuth 클라이언트를 만듭니다. 승인된 JavaScript 원본에 사이트 주소를 등록합니다.</li><li>처음에는 Google OAuth 테스트 사용자에 본인 계정을 등록합니다.</li></ol><div class="form-error" id="connection-error" role="alert"></div><div class="modal-actions"><button class="btn" type="submit" name="mode" value="download">설정 파일 내려받기</button><button class="btn primary" type="submit" name="mode" value="connect">이 브라우저에 적용</button></div></form>`);}
function confirmModal(title,message,action,id){modal(title,`<p class="muted">${esc(message)}</p><div class="modal-actions">${btn('취소','modal-close')}${btn('삭제',action,'primary',`data-id="${id||''}"`)}</div>`);}
function download(name,data,type='application/json'){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function loadScript(url,test){if(test())return;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=url;s.onload=resolve;s.onerror=()=>reject(new Error('연결 라이브러리를 불러오지 못했습니다.'));document.head.append(s);});if(!test())throw new Error('연결 라이브러리를 확인할 수 없습니다.');}
function validateConfig(c){let u;try{u=new URL(c.supabaseUrl);}catch{throw new Error('프로젝트 URL을 확인해 주세요.');}if(u.protocol!=='https:')throw new Error('Supabase URL은 HTTPS여야 합니다.');if(!c.supabaseKey)throw new Error('공개 키를 입력해 주세요.');if(c.supabaseKey.startsWith('sb_secret_'))throw new Error('공개 키만 사용할 수 있습니다.');if(c.supabaseKey.includes('.')){try{const payload=JSON.parse(atob(c.supabaseKey.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')));if(payload.role!=='anon')throw new Error('공개 anon 키만 사용할 수 있습니다.');}catch{throw new Error('유효한 공개 anon 키를 입력해 주세요.');}}else if(!c.supabaseKey.startsWith('sb_publishable_'))throw new Error('Supabase 공개 publishable 키를 입력해 주세요.');}
async function initDb(){if(!config.supabaseUrl||!config.supabaseKey)return;validateConfig(config);await loadScript('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/dist/umd/supabase.js',()=>!!window.supabase);state.db=window.supabase.createClient(config.supabaseUrl,config.supabaseKey,{auth:{storage:sessionStorage,persistSession:true,detectSessionInUrl:false}});state.db.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'){clearPrivate();render();}else if(event==='TOKEN_REFRESHED')state.user=session?.user||null;});const {data:{session},error}=await state.db.auth.getSession();if(error)throw error;if(session){await loadPrivate(session.user);}const {data,error:profileError}=await state.db.from('public_profile').select('data').eq('id',true).maybeSingle();if(profileError)toast('공개 페이지 연결을 확인해 주세요.');if(data)state.profile=normalizeProfile(data.data);}
async function loadPrivate(user){const {data:owner,error:ownerError}=await state.db.from('app_owner').select('owner_id').eq('owner_id',user.id).maybeSingle();if(ownerError)throw ownerError;if(!owner){await state.db.auth.signOut();throw new Error('등록된 소유자 계정이 아닙니다.');}const {data:row,error}=await state.db.from('private_workspace').select('data,revision').eq('owner_id',user.id).maybeSingle();if(error)throw error;if(!row){const {error:insertError}=await state.db.from('private_workspace').insert({owner_id:user.id,data:defaultData(),revision:0});if(insertError)throw insertError;}state.user=user;state.preview=false;state.data=row?normalizeData(row.data):defaultData();state.revision=row?.revision||0;state.dirty=false;state.conflict=false;state.status='저장됨';}
function clearPrivate(){clearTimeout(saveTimer);state.user=null;state.preview=false;state.data=null;state.events=[];state.calendars=[];state.token=null;state.tokenExpiry=0;state.dirty=false;state.conflict=false;state.pageId=null;state.projectId=null;state.status='';state.menu=false;}
let oauthClient;
const CALENDAR_SCOPE='https://www.googleapis.com/auth/calendar.readonly';
async function connectGoogle(){if(state.preview){toast('실제 캘린더 연결은 로그인 후 사용할 수 있습니다.');return;}if(!state.user)return;if(!config.googleClientId){connectionModal();return;}try{await loadScript('https://accounts.google.com/gsi/client',()=>!!window.google?.accounts?.oauth2);oauthClient=window.google.accounts.oauth2.initTokenClient({client_id:config.googleClientId,scope:CALENDAR_SCOPE,callback:async response=>{if(!state.user)return;if(response.error){toast('Google 연결을 완료하지 못했습니다.');return;}if(!window.google.accounts.oauth2.hasGrantedAllScopes(response,CALENDAR_SCOPE)){toast('캘린더 읽기 권한을 허용해 주세요.');return;}state.token=response.access_token;state.tokenExpiry=Date.now()+Number(response.expires_in)*1000;try{state.calendars=await paginatedGoogle('users/me/calendarList',{maxResults:'250'});state.calendarId=state.calendars.find(c=>c.primary)?.id||'primary';await refreshCalendar();toast('Google 캘린더를 연결했습니다.');}catch(error){toast(error.message);}},error_callback:()=>toast('Google 로그인 창을 다시 열어 주세요.')});oauthClient.requestAccessToken({prompt:'select_account'});}catch(error){toast(error.message);}}
async function paginatedGoogle(path,params){const result=[],owner=state.user?.id,token=state.token;let next;do{if(!owner||!token||Date.now()>=state.tokenExpiry)throw new Error('Google 캘린더를 다시 연결해 주세요.');const query=new URLSearchParams({...params,...(next?{pageToken:next}:{})});const response=await fetch(`https://www.googleapis.com/calendar/v3/${path}?${query}`,{headers:{Authorization:`Bearer ${token}`}});if(state.user?.id!==owner||state.token!==token)return [];if(!response.ok){if(response.status===401){state.token=null;state.events=[];state.calendars=[];render();}throw new Error(response.status===401?'Google 연결이 만료되었습니다. 다시 연결해 주세요.':'캘린더 API 설정과 접근 권한을 확인해 주세요.');}const body=await response.json();result.push(...(body.items||[]));next=body.nextPageToken;}while(next);return result;}
let calendarRequest=0;
async function refreshCalendar(){if(!state.token)return;const request=++calendarRequest,month=new Date(state.month),owner=state.user?.id;const min=new Date(month.getFullYear(),month.getMonth(),1);min.setDate(min.getDate()-min.getDay());const max=new Date(min);max.setDate(max.getDate()+42);const now=new Date();const from=new Date(Math.min(min.getTime(),new Date(now.getFullYear(),now.getMonth(),now.getDate()).getTime()));const to=new Date(Math.max(max.getTime(),new Date(now.getFullYear(),now.getMonth(),now.getDate()+1).getTime()));try{const events=await paginatedGoogle(`calendars/${encodeURIComponent(state.calendarId)}/events`,{timeMin:from.toISOString(),timeMax:to.toISOString(),singleEvents:'true',orderBy:'startTime',maxResults:'250',timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone});if(request===calendarRequest&&state.user?.id===owner){state.events=events.filter(e=>e.status!=='cancelled'&&e.start&&e.end);render();}}catch(error){toast(error.message);}}
function disconnectGoogle(){const token=state.token;calendarRequest++;state.token=null;state.tokenExpiry=0;state.events=[];state.calendars=[];render();if(token&&window.google?.accounts?.oauth2)window.google.accounts.oauth2.revoke(token,()=>{});toast('캘린더 연결을 해제했습니다.');}
function normalizeProfile(p){if(!p||typeof p!=='object')throw new Error('공개 페이지 데이터가 올바르지 않습니다.');const txt=x=>typeof x==='string'?x.slice(0,20000):'';return {name:txt(p.name),tagline:txt(p.tagline),bio:txt(p.bio),github:txt(p.github),email:txt(p.email),style:['studio','minimal','editorial'].includes(p.style)?p.style:'studio',projects:Array.isArray(p.projects)?p.projects.slice(0,100).map(x=>({title:txt(x.title),description:txt(x.description),url:txt(x.url)})):[]};}
function normalizeData(raw){if(!raw||typeof raw!=='object'||!['tasks','projects','pages','categories'].every(k=>Array.isArray(raw[k])))throw new Error('플래너 데이터 형식이 올바르지 않습니다.');const txt=x=>typeof x==='string'?x.slice(0,100000):'';const color=x=>/^#[0-9a-f]{6}$/i.test(x)?x:'#4b63df';const id=x=>/^[a-zA-Z0-9_-]{1,80}$/.test(x)?x:uid();const date=x=>/^\d{4}-\d{2}-\d{2}$/.test(x)?x:'';const base=defaultData();const order=raw.settings?.dashboard;return {note:txt(raw.note),categories:raw.categories.slice(0,100).map(c=>({id:id(c.id),name:txt(c.name),color:color(c.color)})),tasks:raw.tasks.slice(0,10000).map(t=>({id:id(t.id),title:txt(t.title),description:txt(t.description),due:date(t.due),status:['todo','doing','done'].includes(t.status)?t.status:'todo',projectId:txt(t.projectId),categoryId:txt(t.categoryId)})),projects:raw.projects.slice(0,1000).map(p=>({id:id(p.id),title:txt(p.title),description:txt(p.description),due:date(p.due),categoryId:txt(p.categoryId),color:color(p.color)})),pages:raw.pages.slice(0,1000).map(p=>({id:id(p.id),title:txt(p.title),favorite:!!p.favorite,blocks:(Array.isArray(p.blocks)?p.blocks:[]).slice(0,5000).map(b=>({id:id(b.id),type:['text','heading','check','bullet','quote','callout','divider'].includes(b.type)?b.type:'text',text:txt(b.text),checked:!!b.checked}))})),settings:{accent:color(raw.settings?.accent),density:raw.settings?.density==='compact'?'compact':'comfortable',dashboard:Array.isArray(order)&&order.length===4&&new Set(order).size===4&&order.every(k=>base.settings.dashboard.includes(k))?order:base.settings.dashboard}};}
function currentPage(){return state.data.pages.find(p=>p.id===state.pageId);}
function move(list,index,delta){const next=index+delta;if(index>=0&&next>=0&&next<list.length)[list[index],list[next]]=[list[next],list[index]];}
document.addEventListener('click',async event=>{
 const target=event.target.closest('[data-action]');if(!target)return;const action=target.dataset.action,id=target.dataset.id;
 try{
 switch(action){
 case 'modal-close':$('#modal').close();break;
 case 'preview':if(state.user){location.hash='today';break;}state.originalProfile=clone(state.profile);state.preview=true;state.data=defaultData();state.view='today';state.projectId=null;state.pageId=null;location.hash='today';render();break;
 case 'exit-preview':if(state.data&&(state.data.tasks.length||state.data.projects.length||state.data.pages.length||state.data.note)&&!confirm('미리보기 내용을 지우고 나갈까요?'))return;const profile=state.originalProfile;clearPrivate();state.profile=profile||defaultProfile();location.hash='home';render();break;
 case 'workspace':location.hash='today';break;
 case 'toggle-menu':state.menu=!state.menu;$('.workspace')?.classList.toggle('menu-open',state.menu);break;
 case 'connection':connectionModal();break;
 case 'logout':await flush();if(state.dirty&&!confirm('저장하지 못한 내용이 있습니다. 로그아웃할까요?'))return;await state.db.auth.signOut();clearPrivate();location.hash='home';render();break;
 case 'add-task':taskModal(null,target.dataset);break;
 case 'edit-task':taskModal(id);break;
 case 'delete-task':confirmModal('할 일 삭제','이 할 일을 삭제할까요?','delete-task-confirm',id);break;
 case 'delete-task-confirm':state.data.tasks=state.data.tasks.filter(t=>t.id!==id);touch();$('#modal').close();render();break;
 case 'add-project':projectModal();break;
 case 'edit-project':projectModal(id);break;
 case 'open-project':state.projectId=id;location.hash='projects';render();break;
 case 'projects-back':state.projectId=null;render();break;
 case 'delete-project':confirmModal('프로젝트 삭제','프로젝트를 삭제하면 연결된 할 일은 프로젝트 밖으로 이동합니다.','delete-project-confirm',id);break;
 case 'delete-project-confirm':state.data.projects=state.data.projects.filter(p=>p.id!==id);state.data.tasks.forEach(t=>{if(t.projectId===id)t.projectId='';});state.projectId=null;touch();$('#modal').close();render();break;
 case 'month-prev':case 'month-next':state.month=new Date(state.month.getFullYear(),state.month.getMonth()+(action==='month-next'?1:-1),1);render();await refreshCalendar();break;
 case 'month-today':state.month=new Date(new Date().getFullYear(),new Date().getMonth(),1);state.selectedDay=today();render();await refreshCalendar();break;
 case 'select-day':state.selectedDay=target.dataset.day;render();break;
 case 'google-connect':await connectGoogle();break;
 case 'google-disconnect':disconnectGoogle();break;
 case 'calendar-refresh':await refreshCalendar();break;
 case 'add-page':{const page={id:uid(),title:'',favorite:false,blocks:[]};state.data.pages.push(page);state.pageId=page.id;touch();render();$('#page-title')?.focus();break;}
 case 'open-page':state.pageId=id;render();break;
 case 'page-favorite':{const page=currentPage();page.favorite=!page.favorite;state.data.pages.sort((a,b)=>Number(b.favorite)-Number(a.favorite));touch();render();break;}
 case 'page-delete':confirmModal('페이지 삭제','페이지와 모든 블록을 삭제할까요?','page-delete-confirm',id);break;
 case 'page-delete-confirm':state.data.pages=state.data.pages.filter(p=>p.id!==id);touch();$('#modal').close();render();break;
 case 'add-block':{const block={id:uid(),type:target.dataset.type,text:'',checked:false};currentPage().blocks.push(block);touch();render();$(`[data-input="block"][data-id="${block.id}"]`)?.focus();break;}
 case 'block-up':case 'block-down':{const blocks=currentPage().blocks;move(blocks,blocks.findIndex(b=>b.id===id),action==='block-up'?-1:1);touch();render();break;}
 case 'block-delete':currentPage().blocks=currentPage().blocks.filter(b=>b.id!==id);touch();render();break;
 case 'widget-up':case 'widget-down':move(state.data.settings.dashboard,state.data.settings.dashboard.indexOf(target.dataset.key),action==='widget-up'?-1:1);touch();render();break;
 case 'add-category':state.data.categories.push({id:uid(),name:'',color:state.data.settings.accent});touch();render();$$('[data-input="category-name"]').at(-1)?.focus();break;
 case 'delete-category':state.data.categories=state.data.categories.filter(c=>c.id!==id);state.data.tasks.forEach(t=>{if(t.categoryId===id)t.categoryId='';});state.data.projects.forEach(p=>{if(p.categoryId===id)p.categoryId='';});touch();render();break;
 case 'edit-profile':profileModal();break;
 case 'profile-project-add':$('#public-project-fields').insertAdjacentHTML('beforeend',publicProjectFields());break;
 case 'profile-project-remove':target.closest('.public-project-fields').remove();break;
 case 'export':download(`workspace-${today()}.json`,JSON.stringify({format:'space-workspace-v1',data:state.data},null,2));toast('백업 파일을 내려받았습니다.');break;
 case 'import':$('#import-file').click();break;
 case 'retry-save':state.conflict=false;state.status='저장 대기';await flush();break;
 case 'reload-data':if(state.dirty&&!confirm('저장되지 않은 수정이 사라집니다. 먼저 백업을 내려받으셨나요?'))return;await loadPrivate(state.user);render();break;
 }
 }catch(error){toast(error.message || '처리하지 못했습니다.');}
});
document.addEventListener('input',event=>{
 const el=event.target,key=el.dataset.input,id=el.dataset.id;if(!key||!state.data)return;
 if(key==='note')state.data.note=el.value;
 else if(key==='block'){const block=currentPage()?.blocks.find(b=>b.id===id);if(block)block.text=el.value;el.style.height='auto';el.style.height=el.scrollHeight+'px';}
 else if(key==='page-title'){currentPage().title=el.value;const list=$(`.page-item[data-id="${state.pageId}"] span`);if(list)list.textContent=el.value||'제목 없음';}
 else if(key==='category-name'){const c=category(id);if(c)c.name=el.value;}
 else if(key==='project-search'){state.query=el.value;const position=el.selectionStart;render();const input=$('#project-search');input.focus();try{input.setSelectionRange(position,position);}catch{}return;}
 touch();
});
document.addEventListener('change',async event=>{
 const el=event.target,key=el.dataset.change,id=el.dataset.id;
 try{
 if(key==='task-check'){state.data.tasks.find(t=>t.id===id).status=el.checked?'done':'todo';touch();render();}
 else if(key==='task-status'){state.data.tasks.find(t=>t.id===id).status=el.value;touch();render();}
 else if(key==='block-check'){currentPage().blocks.find(b=>b.id===id).checked=el.checked;touch();render();}
 else if(key==='accent'){state.data.settings.accent=el.value;touch();render();}
 else if(key==='density'){state.data.settings.density=el.value;touch();render();}
 else if(key==='category-color'){category(id).color=el.value;touch();}
 else if(key==='project-filter'){state.filter=el.value;render();}
 else if(key==='calendar-select'){state.calendarId=el.value;await refreshCalendar();}
 else if(el.id==='import-file'){const file=el.files[0];if(!file)return;if(file.size>10*1024*1024)throw new Error('10MB 이하 파일을 선택해 주세요.');const parsed=JSON.parse(await file.text());if(parsed.format!=='space-workspace-v1')throw new Error('이 플래너에서 내보낸 파일을 선택해 주세요.');const normalized=normalizeData(parsed.data);if(!confirm('현재 플래너 데이터를 백업 내용으로 교체할까요?'))return;state.data=normalized;touch();render();toast('백업을 불러왔습니다.');}
 }catch(error){toast(error.message);}
});
document.addEventListener('submit',async event=>{
 const form=event.target;if(!['login-form','quick-task','task-form','project-form','profile-form','connection-form'].includes(form.id))return;event.preventDefault();const values=Object.fromEntries(new FormData(form));
 try{
 if(form.id==='login-form'){
  const submit=$('button[type=submit]',form);submit.disabled=true;$('#login-error').textContent='';
  try{if(!state.db)await initDb();const response=await fetch(`${config.supabaseUrl.replace(/\/$/,'')}/functions/v1/pin-login`,{method:'POST',headers:{'Content-Type':'application/json',apikey:config.supabaseKey},body:JSON.stringify({pin:values.password})});const body=await response.json();if(!response.ok)throw new Error(body.message||'로그인하지 못했습니다.');const {data,error}=await state.db.auth.setSession({access_token:body.access_token,refresh_token:body.refresh_token});if(error)throw error;await loadPrivate(data.user);form.reset();location.hash='today';render();}catch(error){$('#login-error')&&( $('#login-error').textContent=error.message);submit.disabled=false;}
 }
 else if(form.id==='quick-task'){const title=values.title.trim();if(!title)return;state.data.tasks.push({id:uid(),title,description:'',due:today(),status:'todo',projectId:'',categoryId:''});touch();render();$('#quick-title')?.focus();}
 else if(form.id==='task-form'){if(!values.title.trim())return;const task={...values,title:values.title.trim()};const old=state.data.tasks.find(t=>t.id===form.dataset.id);if(old)Object.assign(old,task);else state.data.tasks.push({id:uid(),...task});touch();$('#modal').close();render();}
 else if(form.id==='project-form'){if(!values.title.trim())return;const project={...values,title:values.title.trim()};const old=state.data.projects.find(p=>p.id===form.dataset.id);if(old)Object.assign(old,project);else state.data.projects.push({id:uid(),...project});touch();$('#modal').close();render();}
 else if(form.id==='profile-form'){const projects=$$('.public-project-fields',form).map(row=>({title:$('[name="public-title"]',row).value,description:$('[name="public-description"]',row).value,url:$('[name="public-url"]',row).value})).filter(p=>p.title||p.description||p.url);const profile=normalizeProfile({...values,projects});if(!state.preview){const {error}=await state.db.from('public_profile').upsert({id:true,data:profile});if(error)throw error;}state.profile=profile;$('#modal').close();render();toast(state.preview?'미리보기에 적용했습니다.':'공개 페이지를 저장했습니다.');}
 else if(form.id==='connection-form'){const next={supabaseUrl:values.supabaseUrl.trim(),supabaseKey:values.supabaseKey.trim(),googleClientId:values.googleClientId.trim()};validateConfig(next);if(event.submitter?.value==='download'){download('config.js',`window.SPACE_CONFIG = ${JSON.stringify(next,null,2)};\n`,'text/javascript');return;}if(state.dirty)throw new Error('먼저 저장하거나 백업한 뒤 연결을 변경해 주세요.');await state.db?.auth.signOut();config=next;localStorage.setItem('space-connection',JSON.stringify(next));state.db=null;clearPrivate();$('#modal').close();location.hash='today';render();await initDb();render();toast('연결 설정을 적용했습니다.');}
 }catch(error){const errorEl=$('#profile-error')||$('#connection-error');if(errorEl)errorEl.textContent=error.message;else toast(error.message);}
});
let dragged;
document.addEventListener('dragstart',event=>{if(event.target.closest('textarea,input,select')){event.preventDefault();return;}const el=event.target.closest('[data-drag]');if(!el)return;dragged={type:el.dataset.drag,id:el.dataset.id};event.dataTransfer?.setData('text/plain',el.dataset.id);});
document.addEventListener('dragover',event=>{const el=event.target.closest('[data-drop]');if(el&&dragged?.type===el.dataset.drop){event.preventDefault();el.classList.add('drop-over');}});
document.addEventListener('dragleave',event=>event.target.closest('[data-drop]')?.classList.remove('drop-over'));
document.addEventListener('dragend',()=>{dragged=null;$$('.drop-over').forEach(el=>el.classList.remove('drop-over'));});
document.addEventListener('drop',event=>{const el=event.target.closest('[data-drop]');if(!el||dragged?.type!==el.dataset.drop)return;event.preventDefault();if(dragged.type==='task'){const task=state.data.tasks.find(t=>t.id===dragged.id);if(task){task.status=el.dataset.status;task.projectId=el.dataset.project;}}else if(dragged.type==='block'){const blocks=currentPage().blocks;const index=blocks.findIndex(b=>b.id===dragged.id),target=blocks.findIndex(b=>b.id===el.dataset.id);if(index>=0&&target>=0){const [block]=blocks.splice(index,1);blocks.splice(target,0,block);}}dragged=null;touch();render();});
document.addEventListener('keydown',event=>{const el=event.target.closest('.project-card');if(el&&['Enter',' '].includes(event.key)){event.preventDefault();el.click();}});
window.addEventListener('hashchange',()=>{state.menu=false;render();});
window.addEventListener('beforeunload',event=>{if(state.dirty){event.preventDefault();event.returnValue='';}});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')flush();});
$('#modal').addEventListener('click',event=>{if(event.target===$('#modal')){const r=$('#modal').getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)$('#modal').close();}});
render();
initDb().then(render).catch(error=>{toast(`계정 연결 확인 · ${error.message}`);render();});
if('serviceWorker' in navigator){navigator.serviceWorker.getRegistrations().then(registrations=>Promise.all(registrations.filter(r=>new URL(r.active?.scriptURL||location.href).pathname.endsWith('/sw.js')).map(r=>r.unregister()))).then(()=>window.caches?.delete('gp-v1')).catch(()=>{});}
