import {it,expect,vi} from 'vitest';
const owner='11111111-1111-1111-1111-111111111111';
const wait=()=>new Promise(r=>setTimeout(r,40));
const response=(v,status=200)=>({ok:status<400,status,json:async()=>v});
const click=action=>{const b=document.querySelector(`[data-action="${action}"]`);expect(b).not.toBeNull();b.click();};
const submit=()=>{const f=document.querySelector('dialog form');const b=f.querySelector('[type=submit]');f.dispatchEvent(new SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:b}));};
it('keeps planner private and empty, then allows real editing and explicit portfolio publication',async()=>{
  HTMLDialogElement.prototype.showModal=function(){this.open=true;};
  HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new Event('close'));};
  localStorage.clear();sessionStorage.clear();window.location.hash='#/';
  document.body.innerHTML='<div id="app"></div><div id="modal-root"></div><div id="toast"></div>';
  let stored=null,revision=0,published=null;const privateReads=[];let labFails=false;const today=new Date();const day=today.getFullYear()+'-'+String(today.getMonth()+1).padStart(2,'0')+'-'+String(today.getDate()).padStart(2,'0');const next=new Date(today);next.setDate(next.getDate()+1);const end=next.getFullYear()+'-'+String(next.getMonth()+1).padStart(2,'0')+'-'+String(next.getDate()).padStart(2,'0');
  const f=vi.spyOn(globalThis,'fetch').mockImplementation(async(url,o={})=>{
    if(url.startsWith('https://www.googleapis.com/calendar/v3')){if(url.includes('/calendarList'))return response({items:[{id:'owner@test.invalid',summary:'Personal',primary:true,selected:true,accessRole:'owner'},{id:'lab@group.calendar.google.com',summary:'<b>Lab</b>',selected:true,accessRole:'reader',backgroundColor:'#123456'}]});if(url.includes('/events?')){const lab=url.includes('lab%40');if(lab&&labFails)return response({error:{message:'Permission lost'}},403);return response({items:[{id:'same-id',summary:lab?'Lab meeting':'Personal meeting',start:{date:day},end:{date:end}}]});}throw Error(url);}
    if(url==='/config.json')return response({url:'https://test.supabase.co',key:'sb_publishable_test',email:'owner@test.invalid',owner});
    if(url.includes('/auth/v1/token'))return response({user:{id:owner},access_token:'token',refresh_token:'refresh',expires_in:3600});
    if(url.includes('/auth/v1/logout'))return response(null);
    if(url.includes('/workspaces')){expect(o.headers.Authorization).toBe('Bearer token');if(!o.method||o.method==='GET'){privateReads.push(url);return response(stored?[{content:stored,revision}]:[]);}const data=JSON.parse(o.body);stored=data.content;revision=data.revision;return response([{content:stored,revision}]);}
    if(url.includes('/portfolio')){if(o.method==='POST'){published=JSON.parse(o.body).content;return response(null);}return response(published?[{content:published}]:[]);}throw Error(url);
  });
  await import('../src/main.js');await wait();
  expect(document.querySelector('.portfolio')).not.toBeNull();expect(document.querySelector('.profile-content h1')).toBeNull();expect(privateReads.length).toBe(0);expect(document.querySelector('[placeholder]')).toBeNull();
  window.location.hash='#/planner';window.dispatchEvent(new Event('hashchange'));await wait();expect(document.querySelector('#login-form')).not.toBeNull();expect(privateReads.length).toBe(0);
  const login=document.querySelector('#login-form');login.elements.password.value='test-password';login.dispatchEvent(new SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:login.querySelector('button')}));await wait();
  expect(document.querySelector('.workspace-shell')).not.toBeNull();expect(document.querySelector('.focus-number').textContent).toContain('0');
  click('view:calendar');expect(document.querySelectorAll('.calendar-cell')).toHaveLength(42);expect(document.querySelector('.day-task-empty').textContent).toBe('할 일 없음');
  click('calendar-mode:week');expect(document.querySelectorAll('.week-column')).toHaveLength(7);const oldWeek=document.querySelector('.calendar-period h2').textContent;click('month-next');expect(document.querySelector('.calendar-period h2').textContent).not.toBe(oldWeek);click('month-prev');expect(document.querySelector('.calendar-period h2').textContent).toBe(oldWeek);
  click('google-connect');expect(document.querySelector('dialog h2').textContent).toBe('Google Calendar 연결');expect(document.querySelector('dialog input[name=googleClientId]').value).toBe('');expect(document.querySelector('[placeholder]')).toBeNull();submit();await wait();expect(document.querySelector('.form-error').textContent).toContain('Client ID');click('google-default');expect(document.querySelector('dialog')).toBeNull();expect(document.querySelector('.workspace-shell')).not.toBeNull();expect(sessionStorage.length).toBeGreaterThan(0);
  click('google-setup');document.querySelector('dialog input[name=googleClientId]').value='123-ui.apps.googleusercontent.com';submit();await wait();
  window.google={accounts:{oauth2:{revoke:vi.fn(),initTokenClient:vi.fn(options=>({requestAccessToken:()=>options.callback({access_token:'google-ui-token',expires_in:3600})}))}}};
  click('google-connect');await wait();expect(document.querySelectorAll('[data-google-calendar]')).toHaveLength(2);expect(document.querySelectorAll('.day-event.google')).toHaveLength(2);expect(document.querySelector('.google-calendar-choice b')).toBeNull();expect(document.querySelector('.google-calendar-list').textContent).toContain('<b>Lab</b>');
  const labEvent=[...document.querySelectorAll('.day-event.google')].find(b=>b.textContent.includes('Lab meeting'));labEvent.click();expect(document.querySelector('dialog').textContent).toContain('Lab meeting');expect(document.querySelector('dialog').textContent).toContain('<b>Lab</b>');click('close');
  const labToggle=document.querySelector('[data-google-calendar="lab@group.calendar.google.com"]');labToggle.checked=false;labToggle.dispatchEvent(new Event('change',{bubbles:true}));await wait();expect(document.querySelectorAll('.day-event.google')).toHaveLength(1);click('save');await wait();expect(stored.googleCalendarIds).toEqual(['owner@test.invalid']);
  click('google-disconnect');expect(document.querySelector('.google-calendar-list')).toBeNull();click('google-connect');await wait();expect(document.querySelectorAll('.day-event.google')).toHaveLength(1);expect(document.querySelector('[data-google-calendar="lab@group.calendar.google.com"]').checked).toBe(false);
  const labAgain=document.querySelector('[data-google-calendar="lab@group.calendar.google.com"]');labAgain.checked=true;labAgain.dispatchEvent(new Event('change',{bubbles:true}));await wait();expect(document.querySelectorAll('.day-event.google')).toHaveLength(2);
  labFails=true;click('google-refresh');await wait();expect(document.querySelectorAll('.day-event.google')).toHaveLength(1);expect(document.querySelector('.calendar-error').textContent).toContain('Permission lost');labFails=false;click('google-disconnect');delete window.google;click('view:today');
  click('new-task');expect(document.querySelector('dialog input[name=title]').value).toBe('');document.querySelector('dialog input[name=title]').value='<script>private task</script>';submit();await wait();expect(document.querySelector('.task-title').textContent).toBe('<script>private task</script>');expect(document.querySelector('.task-title script')).toBeNull();
  click('save');await wait();expect(document.querySelector('#toast').textContent).not.toContain('is not defined');expect(stored,document.querySelector('#toast').textContent+' '+document.querySelector('#save-status').textContent).not.toBeNull();expect(stored.tasks[0].title).toBe('<script>private task</script>');
  // A weekly task and daily task are the same record, including completion state.
  click('view:weekly');expect(document.querySelectorAll('.weekly-todo-day')).toHaveLength(7);
  click('new-task-day:'+day);expect(document.querySelector('dialog input[name=date]').value).toBe(day);document.querySelector('dialog input[name=title]').value='Shared weekly task';submit();await wait();
  const weeklyPlan=document.querySelector('#weekly-plan');weeklyPlan.value='Private weekly plan';weeklyPlan.dispatchEvent(new Event('input',{bubbles:true}));
  click('view:today');expect(document.querySelector('.task-panel').textContent).toContain('Shared weekly task');const sharedTaskButton=[...document.querySelectorAll('.task-title')].find(x=>x.textContent==='Shared weekly task');const sharedTaskId=sharedTaskButton.dataset.action.split(':')[1];click('task-toggle:'+sharedTaskId);
  click('view:weekly');const weeklyShared=[...document.querySelectorAll('.weekly-task')].find(x=>x.textContent.includes('Shared weekly task'));expect(weeklyShared.classList.contains('done')).toBe(true);expect(document.querySelector('#weekly-plan').value).toBe('Private weekly plan');
  click('view:plans');const dailyPlan=document.querySelector('#plan-daily');dailyPlan.value='Private daily plan';dailyPlan.dispatchEvent(new Event('input',{bubbles:true}));expect(document.querySelector('#plan-weekly').value).toBe('Private weekly plan');
  click('new-deadline');expect(document.querySelector('dialog input[name=title]').value).toBe('');document.querySelector('dialog input[name=title]').value='<b>Important</b>';const due=new Date(today);due.setDate(due.getDate()+3);const dueDate=due.getFullYear()+'-'+String(due.getMonth()+1).padStart(2,'0')+'-'+String(due.getDate()).padStart(2,'0');document.querySelector('dialog input[name=date]').value=dueDate;submit();await wait();
  click('view:today');expect(document.querySelector('#daily-plan').value).toBe('Private daily plan');expect(document.querySelector('.deadline-item strong').textContent).toBe('D-3');expect(document.querySelector('.deadline-item span').textContent).toBe('<b>Important</b>');expect(document.querySelector('.deadline-item b')).toBeNull();
  click('save');await wait();expect(stored.tasks.filter(x=>x.title==='Shared weekly task')).toHaveLength(1);expect(stored.tasks.find(x=>x.title==='Shared weekly task').status).toBe('done');expect(stored.dailyPlans[day]).toBe('Private daily plan');expect(Object.values(stored.weeklyPlans)).toContain('Private weekly plan');expect(stored.deadlines[0].date).toBe(dueDate);
  click('new-page');document.querySelector('dialog input[name=title]').value='Private note';submit();await wait();click('new-block');document.querySelector('dialog textarea[name=text]').value='Private page body';submit();await wait();expect(document.querySelector('.document-blocks').textContent).toContain('Private page body');
  click('portfolio');const name=document.querySelector('.portfolio-form input[name=name]');name.value='Published name';name.dispatchEvent(new Event('input',{bubbles:true}));click('save');await wait();expect(published).toBeNull();click('publish');await wait();expect(published.name).toBe('Published name');expect(JSON.stringify(published)).not.toContain('Private page body');expect(JSON.stringify(published)).not.toContain('Private daily plan');expect(JSON.stringify(published)).not.toContain('Important');
  click('logout');await wait();expect(document.querySelector('#login-form')).not.toBeNull();expect(document.body.textContent).not.toContain('Private page body');expect(sessionStorage.length).toBe(0);expect(localStorage.getItem('folio:workspace')).toBeNull();
  window.location.hash='#/';window.dispatchEvent(new Event('hashchange'));await wait();expect(document.querySelector('.profile-content h1').textContent).toBe('Published name');expect(document.body.textContent).not.toContain('private task');f.mockRestore();
});
